/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.willhaycode.lipwig;

import org.junit.Test;

import junit.framework.Assert;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Lipwig lw = new Lipwig("Hello");
    }
}
