/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.willhaycode.lipwig;

import static org.junit.Assert.*;

import org.junit.Test;

public class LibraryTest {
  @Test
  public void testSomeLibraryMethod() {
    Lipwig lw = new Lipwig("Hello");
  }
}
