/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.willhaycode.lipwig;

public class Lipwig {
  public Lipwig(String message) {
    System.out.println(message);
  }
}
